#!/usr/bin/env python3
"""Generate Lean code for `octic_pure_identity` — the deg-7 cancellation
algebraic identity. Analog of `septic_pure_identity` (session 18) at
one degree higher.

The identity:
  ½·W7 + ⅓·y3_7 − ¼·y4_7 + ⅕·y5_7 − ⅙·y6_7 + ⅐·z⁷ − bch_septic_term = 0

where:
- z = a + b
- T_k = y_dk for k=2..6 (deg-k part of y = exp(a)·exp(b) − 1)
- W7 = 2·y_d7 − (y²)_d7
- y_d7 = sum over i+j=7, i,j≥0 of a^i·b^j/(i!·j!) (8 terms)
- (y²)_d7 = sum over k+l=7, k,l≥1 of T_k·T_l (6 terms)
- y3_7 = (y³)_d7 = sum over compositions of 7 into 3 parts ≥ 1 (15 terms)
- y4_7 = (y⁴)_d7 (20 terms)
- y5_7 = (y⁵)_d7 (15 terms)
- y6_7 = (y⁶)_d7 (6 terms — 6 positions for the single T_2 among 5 z's)
- z⁷ = (y⁷)_d7

Output is a Lean snippet to paste into `BCH/Basic.lean` right after
`septic_pure_identity` (~line 11108).

The proof template mirrors `septic_pure_identity`:
  intro [let names];
  show _ = (0 : 𝔸);
  simp only [show T₂ = ..., show T₃ = ..., ...];
  unfold bch_septic_term;
  simp only [pow_succ, pow_zero, one_mul, smul_sub, smul_add, smul_neg, smul_smul,
    mul_smul_comm, smul_mul_assoc, mul_add, add_mul, mul_sub, sub_mul, ← mul_assoc];
  match_scalars <;> ring
"""
from itertools import product
from fractions import Fraction
from math import factorial


def compositions(n, parts):
    """Enumerate all compositions of n into `parts` ordered positive integers."""
    if parts == 1:
        yield (n,)
        return
    for first in range(1, n - parts + 2):
        for rest in compositions(n - first, parts - 1):
            yield (first,) + rest


def t_expr(k):
    """Lean expression for T_k (k=1..6) using the convention z = T_1, T_k for k=2..6."""
    if k == 1:
        return "z"
    return f"T{subscript(k)}"


def subscript(n):
    return ''.join('₀₁₂₃₄₅₆₇₈₉'[int(d)] for d in str(n))


def composition_term(comp):
    """A composition (k_1, ..., k_n) gives the Lean product T_{k_1} * T_{k_2} * ... * T_{k_n}."""
    return ' * '.join(t_expr(k) for k in comp)


def power_of_z_or_T2(z_count, T2_count):
    """For y6_7 with (z, z, z, z, z, T_2) in some order."""
    pass


def main():
    print("-- ===================================")
    print("-- octic_pure_identity (deg-7 cancellation)")
    print("-- Generated by scripts/gen_octic_pure_identity.py")
    print("-- ===================================")
    print()
    print("set_option maxHeartbeats 64000000 in")
    print("omit [NormOneClass 𝔸] [CompleteSpace 𝔸] in")
    print("/-- **Eighth-order BCH: degree-7 cancellation identity (octic_pure_identity)**")
    print("")
    print("Analog of `septic_pure_identity` at one degree higher. After substituting")
    print("ea → exp(a), eb → exp(b), the deg-7 part of")
    print("  `½W_H1 + ⅓y³ − ¼y⁴ + ⅕y⁵ − ⅙y⁶ + ⅐y⁷ − C₃ − C₄ − C₅ − C₆ − C₇`")
    print("vanishes. This identity expresses that vanishing as an explicit pure {a, b}")
    print("ring identity, with the deg-7 leading term `bch_septic_term`.")
    print("")
    print("Notation:")
    print("- `z = a + b`")
    print("- `T_k = y_dk` for k = 2..6 (deg-k of `y = exp(a)·exp(b) − 1`)")
    print("- `W7 = 2·y_d7 − (y²)_d7`")
    print("- `y3_7 = (y³)_d7`, `y4_7 = (y⁴)_d7`, `y5_7 = (y⁵)_d7`,")
    print("  `y6_7 = (y⁶)_d7`, `(y⁷)_d7 = z⁷`")
    print("")
    print("Foundation for the small-s case of `norm_bch_octic_remainder_le`")
    print("(future), the deg-8 analog of `norm_bch_septic_remainder_le`. -/")
    print("private theorem octic_pure_identity (𝕂 : Type*) [RCLike 𝕂] {𝔸 : Type*}")
    print("    [NormedRing 𝔸] [NormedAlgebra 𝕂 𝔸] (a b : 𝔸) :")

    # Generate let bindings.
    # T_2
    print("    let z : 𝔸 := a + b")
    print("    let T₂ : 𝔸 := a * b + (2 : 𝕂)⁻¹ • a ^ 2 + (2 : 𝕂)⁻¹ • b ^ 2")

    # T_3 = ⅙a³ + ½a²b + ½ab² + ⅙b³
    print("    let T₃ : 𝔸 := (6 : 𝕂)⁻¹ • a ^ 3 + (2 : 𝕂)⁻¹ • (a ^ 2 * b) +")
    print("        (2 : 𝕂)⁻¹ • (a * b ^ 2) + (6 : 𝕂)⁻¹ • b ^ 3")

    # T_4
    print("    let T₄ : 𝔸 := (24 : 𝕂)⁻¹ • a ^ 4 + (6 : 𝕂)⁻¹ • (a ^ 3 * b) +")
    print("        (4 : 𝕂)⁻¹ • (a ^ 2 * b ^ 2) + (6 : 𝕂)⁻¹ • (a * b ^ 3) +")
    print("        (24 : 𝕂)⁻¹ • b ^ 4")

    # T_5
    print("    let T₅ : 𝔸 := (120 : 𝕂)⁻¹ • a ^ 5 + (24 : 𝕂)⁻¹ • (a ^ 4 * b) +")
    print("        (12 : 𝕂)⁻¹ • (a ^ 3 * b ^ 2) + (12 : 𝕂)⁻¹ • (a ^ 2 * b ^ 3) +")
    print("        (24 : 𝕂)⁻¹ • (a * b ^ 4) + (120 : 𝕂)⁻¹ • b ^ 5")

    # T_6 = sum_{i+j=6, i,j ≥ 0} a^i·b^j/(i!·j!)
    # i=0: b^6/720, i=1: a·b^5/120, i=2: a²·b⁴/48, i=3: a³·b³/36, i=4: a⁴·b²/48, i=5: a⁵·b/120, i=6: a⁶/720
    print("    let T₆ : 𝔸 := (720 : 𝕂)⁻¹ • a ^ 6 + (120 : 𝕂)⁻¹ • (a ^ 5 * b) +")
    print("        (48 : 𝕂)⁻¹ • (a ^ 4 * b ^ 2) + (36 : 𝕂)⁻¹ • (a ^ 3 * b ^ 3) +")
    print("        (48 : 𝕂)⁻¹ • (a ^ 2 * b ^ 4) + (120 : 𝕂)⁻¹ • (a * b ^ 5) +")
    print("        (720 : 𝕂)⁻¹ • b ^ 6")

    # W7 = 2·y_d7 - (y²)_d7
    # y_d7 = a^7/5040 + a^6b/720 + a^5b^2/240 + a^4b^3/144 + a^3b^4/144 + a^2b^5/240 + ab^6/720 + b^7/5040
    # (y²)_d7 = z·T_6 + T_2·T_5 + T_3·T_4 + T_4·T_3 + T_5·T_2 + T_6·z
    # Use 2·y_d7 = 2/i!·j! coefficient.
    # 2/5040 = 1/2520, 2/720 = 1/360, 2/240 = 1/120, 2/144 = 1/72
    print("    -- W7 = 2·y_d7 − (y²)_d7, where (y²)_d7 = z·T_6 + T_2·T_5 + T_3·T_4 + T_4·T_3 + T_5·T_2 + T_6·z")
    print("    let W7 : 𝔸 := (2520 : 𝕂)⁻¹ • a ^ 7 + (360 : 𝕂)⁻¹ • (a ^ 6 * b) +")
    print("        (120 : 𝕂)⁻¹ • (a ^ 5 * b ^ 2) + (72 : 𝕂)⁻¹ • (a ^ 4 * b ^ 3) +")
    print("        (72 : 𝕂)⁻¹ • (a ^ 3 * b ^ 4) + (120 : 𝕂)⁻¹ • (a ^ 2 * b ^ 5) +")
    print("        (360 : 𝕂)⁻¹ • (a * b ^ 6) + (2520 : 𝕂)⁻¹ • b ^ 7 -")
    print("        (z * T₆ + T₂ * T₅ + T₃ * T₄ + T₄ * T₃ + T₅ * T₂ + T₆ * z)")

    # y3_7: 15 compositions of 7 into 3 parts.
    comps_3 = list(compositions(7, 3))
    assert len(comps_3) == 15
    print(f"    -- y3_7 = (y³)_d7: {len(comps_3)} terms from k+l+m=7, each ≥ 1")
    print("    let y3_7 : 𝔸 :=")
    for i, c in enumerate(comps_3):
        prefix = "        " if i == 0 else "        + "
        print(f"{prefix}{composition_term(c)}")

    # y4_7: 20 compositions of 7 into 4 parts.
    comps_4 = list(compositions(7, 4))
    assert len(comps_4) == 20
    print(f"    -- y4_7 = (y⁴)_d7: {len(comps_4)} terms from k_1+k_2+k_3+k_4=7, each ≥ 1")
    print("    let y4_7 : 𝔸 :=")
    for i, c in enumerate(comps_4):
        prefix = "        " if i == 0 else "        + "
        print(f"{prefix}{composition_term(c)}")

    # y5_7: 15 compositions of 7 into 5 parts.
    comps_5 = list(compositions(7, 5))
    assert len(comps_5) == 15
    print(f"    -- y5_7 = (y⁵)_d7: {len(comps_5)} terms from k_1+...+k_5=7, each ≥ 1")
    print("    let y5_7 : 𝔸 :=")
    for i, c in enumerate(comps_5):
        prefix = "        " if i == 0 else "        + "
        print(f"{prefix}{composition_term(c)}")

    # y6_7: 6 compositions of 7 into 6 parts.
    comps_6 = list(compositions(7, 6))
    assert len(comps_6) == 6
    print(f"    -- y6_7 = (y⁶)_d7: {len(comps_6)} terms (single T_2 among 5 z's)")
    print("    let y6_7 : 𝔸 :=")
    for i, c in enumerate(comps_6):
        prefix = "        " if i == 0 else "        + "
        print(f"{prefix}{composition_term(c)}")

    # (y⁷)_d7 = z⁷
    print("    -- (y⁷)_d7 = z⁷ (only (1,1,1,1,1,1,1))")
    print("    (2 : 𝕂)⁻¹ • W7 + (3 : 𝕂)⁻¹ • y3_7 - (4 : 𝕂)⁻¹ • y4_7 +")
    print("      (5 : 𝕂)⁻¹ • y5_7 - (6 : 𝕂)⁻¹ • y6_7 + (7 : 𝕂)⁻¹ • z ^ 7 -")
    print("      bch_septic_term 𝕂 a b = 0 := by")
    print("  intro z T₂ T₃ T₄ T₅ T₆ W7 y3_7 y4_7 y5_7 y6_7")
    print("  show _ = (0 : 𝔸)")
    print("  simp only [show z = a + b from rfl,")
    print("    show T₂ = a * b + (2 : 𝕂)⁻¹ • a ^ 2 + (2 : 𝕂)⁻¹ • b ^ 2 from rfl,")
    print("    show T₃ = (6 : 𝕂)⁻¹ • a ^ 3 + (2 : 𝕂)⁻¹ • (a ^ 2 * b) +")
    print("        (2 : 𝕂)⁻¹ • (a * b ^ 2) + (6 : 𝕂)⁻¹ • b ^ 3 from rfl,")
    print("    show T₄ = (24 : 𝕂)⁻¹ • a ^ 4 + (6 : 𝕂)⁻¹ • (a ^ 3 * b) +")
    print("        (4 : 𝕂)⁻¹ • (a ^ 2 * b ^ 2) + (6 : 𝕂)⁻¹ • (a * b ^ 3) +")
    print("        (24 : 𝕂)⁻¹ • b ^ 4 from rfl,")
    print("    show T₅ = (120 : 𝕂)⁻¹ • a ^ 5 + (24 : 𝕂)⁻¹ • (a ^ 4 * b) +")
    print("        (12 : 𝕂)⁻¹ • (a ^ 3 * b ^ 2) + (12 : 𝕂)⁻¹ • (a ^ 2 * b ^ 3) +")
    print("        (24 : 𝕂)⁻¹ • (a * b ^ 4) + (120 : 𝕂)⁻¹ • b ^ 5 from rfl,")
    print("    show T₆ = (720 : 𝕂)⁻¹ • a ^ 6 + (120 : 𝕂)⁻¹ • (a ^ 5 * b) +")
    print("        (48 : 𝕂)⁻¹ • (a ^ 4 * b ^ 2) + (36 : 𝕂)⁻¹ • (a ^ 3 * b ^ 3) +")
    print("        (48 : 𝕂)⁻¹ • (a ^ 2 * b ^ 4) + (120 : 𝕂)⁻¹ • (a * b ^ 5) +")
    print("        (720 : 𝕂)⁻¹ • b ^ 6 from rfl,")
    print("    show W7 = (2520 : 𝕂)⁻¹ • a ^ 7 + (360 : 𝕂)⁻¹ • (a ^ 6 * b) +")
    print("        (120 : 𝕂)⁻¹ • (a ^ 5 * b ^ 2) + (72 : 𝕂)⁻¹ • (a ^ 4 * b ^ 3) +")
    print("        (72 : 𝕂)⁻¹ • (a ^ 3 * b ^ 4) + (120 : 𝕂)⁻¹ • (a ^ 2 * b ^ 5) +")
    print("        (360 : 𝕂)⁻¹ • (a * b ^ 6) + (2520 : 𝕂)⁻¹ • b ^ 7 -")
    print("        (z * T₆ + T₂ * T₅ + T₃ * T₄ + T₄ * T₃ + T₅ * T₂ + T₆ * z) from rfl,")
    # y3_7 show clause.
    print("    show y3_7 =")
    for i, c in enumerate(comps_3):
        prefix = "        " if i == 0 else "        + "
        print(f"{prefix}{composition_term(c)}")
    print("        from rfl,")
    # y4_7 show clause.
    print("    show y4_7 =")
    for i, c in enumerate(comps_4):
        prefix = "        " if i == 0 else "        + "
        print(f"{prefix}{composition_term(c)}")
    print("        from rfl,")
    # y5_7 show clause.
    print("    show y5_7 =")
    for i, c in enumerate(comps_5):
        prefix = "        " if i == 0 else "        + "
        print(f"{prefix}{composition_term(c)}")
    print("        from rfl,")
    # y6_7 show clause.
    print("    show y6_7 =")
    for i, c in enumerate(comps_6):
        prefix = "        " if i == 0 else "        + "
        print(f"{prefix}{composition_term(c)}")
    print("        from rfl]")
    print("  unfold bch_septic_term")
    print("  simp only [pow_succ, pow_zero, one_mul, smul_sub, smul_add, smul_neg, smul_smul,")
    print("    mul_smul_comm, smul_mul_assoc, mul_add, add_mul, mul_sub, sub_mul, ← mul_assoc]")
    print("  match_scalars <;> ring")


if __name__ == "__main__":
    main()
