#!/usr/bin/env python3
"""Generate Lean code for `nonic_pure_identity` — the deg-8 cancellation
algebraic identity. Analog of `octic_pure_identity` at one degree higher.

The identity:
  ½·W8 + ⅓·y3_8 − ¼·y4_8 + ⅕·y5_8 − ⅙·y6_8 + ⅐·y7_8 − ⅛·z⁸ − bch_octic_term = 0

where:
- z = a + b
- T_k = y_dk for k=2..7 (deg-k part of y = exp(a)·exp(b) − 1)
- W8 = 2·y_d8 − (y²)_d8
- y_d8 = sum over i+j=8, i,j≥0 of a^i·b^j/(i!·j!) (9 terms)
- (y²)_d8 = sum over k+l=8, k,l≥1 of T_k·T_l (7 terms)
- y3_8 = (y³)_d8 = sum over compositions of 8 into 3 parts ≥ 1 (21 terms)
- y4_8 = (y⁴)_d8 (35 terms)
- y5_8 = (y⁵)_d8 (35 terms)
- y6_8 = (y⁶)_d8 (21 terms)
- y7_8 = (y⁷)_d8 (7 terms — 7 positions of T_2 among 6 z's)
- z⁸ = (y⁸)_d8

Output is a Lean snippet to paste into `BCH/Basic.lean` right after
`octic_pure_identity`.
"""


def compositions(n, parts):
    """Enumerate all compositions of n into `parts` ordered positive integers."""
    if parts == 1:
        yield (n,)
        return
    for first in range(1, n - parts + 2):
        for rest in compositions(n - first, parts - 1):
            yield (first,) + rest


def t_expr(k):
    """Lean expression for T_k (k=1..7) using the convention z = T_1, T_k for k=2..7."""
    if k == 1:
        return "z"
    return f"T{subscript(k)}"


def subscript(n):
    return ''.join('₀₁₂₃₄₅₆₇₈₉'[int(d)] for d in str(n))


def composition_term(comp):
    return ' * '.join(t_expr(k) for k in comp)


def main():
    print("-- ===================================")
    print("-- nonic_pure_identity (deg-8 cancellation)")
    print("-- Generated by scripts/gen_nonic_pure_identity.py")
    print("-- ===================================")
    print()
    print("set_option maxHeartbeats 128000000 in")
    print("omit [NormOneClass 𝔸] [CompleteSpace 𝔸] in")
    print("/-- **Ninth-order BCH: degree-8 cancellation identity (nonic_pure_identity)**")
    print("")
    print("Analog of `octic_pure_identity` at one degree higher. After substituting")
    print("ea → exp(a), eb → exp(b), the deg-8 part of")
    print("  `½W_H1 + ⅓y³ − ¼y⁴ + ⅕y⁵ − ⅙y⁶ + ⅐y⁷ − ⅛y⁸ − C₃ − C₄ − C₅ − C₆ − C₇ − C₈`")
    print("vanishes. This identity expresses that vanishing as an explicit pure {a, b}")
    print("ring identity, with the deg-8 leading term `bch_octic_term`.")
    print("")
    print("Notation:")
    print("- `z = a + b`")
    print("- `T_k = y_dk` for k = 2..7 (deg-k of `y = exp(a)·exp(b) − 1`)")
    print("- `W8 = 2·y_d8 − (y²)_d8`")
    print("- `y3_8 = (y³)_d8`, `y4_8 = (y⁴)_d8`, `y5_8 = (y⁵)_d8`,")
    print("  `y6_8 = (y⁶)_d8`, `y7_8 = (y⁷)_d8`, `(y⁸)_d8 = z⁸`")
    print("")
    print("Foundation for stepping stone 1 (`symmetric_bch_septic_sub_poly_axiom`)")
    print("discharge — the deg-9 analog of T2-F7e. -/")
    print("private theorem nonic_pure_identity (𝕂 : Type*) [RCLike 𝕂] {𝔸 : Type*}")
    print("    [NormedRing 𝔸] [NormedAlgebra 𝕂 𝔸] (a b : 𝔸) :")

    # T_2
    print("    let z : 𝔸 := a + b")
    print("    let T₂ : 𝔸 := a * b + (2 : 𝕂)⁻¹ • a ^ 2 + (2 : 𝕂)⁻¹ • b ^ 2")
    # T_3
    print("    let T₃ : 𝔸 := (6 : 𝕂)⁻¹ • a ^ 3 + (2 : 𝕂)⁻¹ • (a ^ 2 * b) +")
    print("        (2 : 𝕂)⁻¹ • (a * b ^ 2) + (6 : 𝕂)⁻¹ • b ^ 3")
    # T_4
    print("    let T₄ : 𝔸 := (24 : 𝕂)⁻¹ • a ^ 4 + (6 : 𝕂)⁻¹ • (a ^ 3 * b) +")
    print("        (4 : 𝕂)⁻¹ • (a ^ 2 * b ^ 2) + (6 : 𝕂)⁻¹ • (a * b ^ 3) +")
    print("        (24 : 𝕂)⁻¹ • b ^ 4")
    # T_5
    print("    let T₅ : 𝔸 := (120 : 𝕂)⁻¹ • a ^ 5 + (24 : 𝕂)⁻¹ • (a ^ 4 * b) +")
    print("        (12 : 𝕂)⁻¹ • (a ^ 3 * b ^ 2) + (12 : 𝕂)⁻¹ • (a ^ 2 * b ^ 3) +")
    print("        (24 : 𝕂)⁻¹ • (a * b ^ 4) + (120 : 𝕂)⁻¹ • b ^ 5")
    # T_6
    print("    let T₆ : 𝔸 := (720 : 𝕂)⁻¹ • a ^ 6 + (120 : 𝕂)⁻¹ • (a ^ 5 * b) +")
    print("        (48 : 𝕂)⁻¹ • (a ^ 4 * b ^ 2) + (36 : 𝕂)⁻¹ • (a ^ 3 * b ^ 3) +")
    print("        (48 : 𝕂)⁻¹ • (a ^ 2 * b ^ 4) + (120 : 𝕂)⁻¹ • (a * b ^ 5) +")
    print("        (720 : 𝕂)⁻¹ • b ^ 6")
    # T_7 = sum_{i+j=7, i,j ≥ 0} a^i·b^j/(i!·j!)
    # 1/(0!·7!) = 1/5040, 1/(1!·6!) = 1/720, 1/(2!·5!) = 1/240, 1/(3!·4!) = 1/144
    print("    let T₇ : 𝔸 := (5040 : 𝕂)⁻¹ • a ^ 7 + (720 : 𝕂)⁻¹ • (a ^ 6 * b) +")
    print("        (240 : 𝕂)⁻¹ • (a ^ 5 * b ^ 2) + (144 : 𝕂)⁻¹ • (a ^ 4 * b ^ 3) +")
    print("        (144 : 𝕂)⁻¹ • (a ^ 3 * b ^ 4) + (240 : 𝕂)⁻¹ • (a ^ 2 * b ^ 5) +")
    print("        (720 : 𝕂)⁻¹ • (a * b ^ 6) + (5040 : 𝕂)⁻¹ • b ^ 7")

    # W8 = 2·y_d8 - (y²)_d8
    # y_d8 = sum_{i+j=8} a^i·b^j/(i!·j!) — 9 monomials.
    # i=0: b^8/40320, i=1: a·b^7/5040, i=2: a²·b⁶/1440, i=3: a³·b⁵/720, i=4: a⁴·b⁴/576, etc. by symmetry.
    # 2·coef: 2/40320 = 1/20160, 2/5040 = 1/2520, 2/1440 = 1/720, 2/720 = 1/360, 2/576 = 1/288
    # (y²)_d8 = z·T_7 + T_2·T_6 + T_3·T_5 + T_4·T_4 + T_5·T_3 + T_6·T_2 + T_7·z (7 products)
    print("    -- W8 = 2·y_d8 − (y²)_d8, where (y²)_d8 = z·T_7 + T_2·T_6 + T_3·T_5 + T_4·T_4 + T_5·T_3 + T_6·T_2 + T_7·z")
    print("    let W8 : 𝔸 := (20160 : 𝕂)⁻¹ • a ^ 8 + (2520 : 𝕂)⁻¹ • (a ^ 7 * b) +")
    print("        (720 : 𝕂)⁻¹ • (a ^ 6 * b ^ 2) + (360 : 𝕂)⁻¹ • (a ^ 5 * b ^ 3) +")
    print("        (288 : 𝕂)⁻¹ • (a ^ 4 * b ^ 4) + (360 : 𝕂)⁻¹ • (a ^ 3 * b ^ 5) +")
    print("        (720 : 𝕂)⁻¹ • (a ^ 2 * b ^ 6) + (2520 : 𝕂)⁻¹ • (a * b ^ 7) +")
    print("        (20160 : 𝕂)⁻¹ • b ^ 8 -")
    print("        (z * T₇ + T₂ * T₆ + T₃ * T₅ + T₄ * T₄ + T₅ * T₃ + T₆ * T₂ + T₇ * z)")

    # Composition-based y_k_8 polynomials.
    for k, expected_count in [(3, 21), (4, 35), (5, 35), (6, 21), (7, 7)]:
        comps = list(compositions(8, k))
        assert len(comps) == expected_count, f"expected {expected_count}, got {len(comps)}"
        print(f"    -- y{k}_8 = (y^{k})_d8: {expected_count} terms from k_1+...+k_{k}=8, each ≥ 1")
        print(f"    let y{k}_8 : 𝔸 :=")
        for i, c in enumerate(comps):
            prefix = "        " if i == 0 else "        + "
            print(f"{prefix}{composition_term(c)}")

    # The identity statement.
    print("    -- (y⁸)_d8 = z⁸ (only (1,1,1,1,1,1,1,1))")
    print("    (2 : 𝕂)⁻¹ • W8 + (3 : 𝕂)⁻¹ • y3_8 - (4 : 𝕂)⁻¹ • y4_8 +")
    print("      (5 : 𝕂)⁻¹ • y5_8 - (6 : 𝕂)⁻¹ • y6_8 + (7 : 𝕂)⁻¹ • y7_8 -")
    print("      (8 : 𝕂)⁻¹ • z ^ 8 - bch_octic_term 𝕂 a b = 0 := by")
    print("  intro z T₂ T₃ T₄ T₅ T₆ T₇ W8 y3_8 y4_8 y5_8 y6_8 y7_8")
    print("  show _ = (0 : 𝔸)")
    print("  simp only [show z = a + b from rfl,")
    print("    show T₂ = a * b + (2 : 𝕂)⁻¹ • a ^ 2 + (2 : 𝕂)⁻¹ • b ^ 2 from rfl,")
    print("    show T₃ = (6 : 𝕂)⁻¹ • a ^ 3 + (2 : 𝕂)⁻¹ • (a ^ 2 * b) +")
    print("        (2 : 𝕂)⁻¹ • (a * b ^ 2) + (6 : 𝕂)⁻¹ • b ^ 3 from rfl,")
    print("    show T₄ = (24 : 𝕂)⁻¹ • a ^ 4 + (6 : 𝕂)⁻¹ • (a ^ 3 * b) +")
    print("        (4 : 𝕂)⁻¹ • (a ^ 2 * b ^ 2) + (6 : 𝕂)⁻¹ • (a * b ^ 3) +")
    print("        (24 : 𝕂)⁻¹ • b ^ 4 from rfl,")
    print("    show T₅ = (120 : 𝕂)⁻¹ • a ^ 5 + (24 : 𝕂)⁻¹ • (a ^ 4 * b) +")
    print("        (12 : 𝕂)⁻¹ • (a ^ 3 * b ^ 2) + (12 : 𝕂)⁻¹ • (a ^ 2 * b ^ 3) +")
    print("        (24 : 𝕂)⁻¹ • (a * b ^ 4) + (120 : 𝕂)⁻¹ • b ^ 5 from rfl,")
    print("    show T₆ = (720 : 𝕂)⁻¹ • a ^ 6 + (120 : 𝕂)⁻¹ • (a ^ 5 * b) +")
    print("        (48 : 𝕂)⁻¹ • (a ^ 4 * b ^ 2) + (36 : 𝕂)⁻¹ • (a ^ 3 * b ^ 3) +")
    print("        (48 : 𝕂)⁻¹ • (a ^ 2 * b ^ 4) + (120 : 𝕂)⁻¹ • (a * b ^ 5) +")
    print("        (720 : 𝕂)⁻¹ • b ^ 6 from rfl,")
    print("    show T₇ = (5040 : 𝕂)⁻¹ • a ^ 7 + (720 : 𝕂)⁻¹ • (a ^ 6 * b) +")
    print("        (240 : 𝕂)⁻¹ • (a ^ 5 * b ^ 2) + (144 : 𝕂)⁻¹ • (a ^ 4 * b ^ 3) +")
    print("        (144 : 𝕂)⁻¹ • (a ^ 3 * b ^ 4) + (240 : 𝕂)⁻¹ • (a ^ 2 * b ^ 5) +")
    print("        (720 : 𝕂)⁻¹ • (a * b ^ 6) + (5040 : 𝕂)⁻¹ • b ^ 7 from rfl,")
    print("    show W8 = (20160 : 𝕂)⁻¹ • a ^ 8 + (2520 : 𝕂)⁻¹ • (a ^ 7 * b) +")
    print("        (720 : 𝕂)⁻¹ • (a ^ 6 * b ^ 2) + (360 : 𝕂)⁻¹ • (a ^ 5 * b ^ 3) +")
    print("        (288 : 𝕂)⁻¹ • (a ^ 4 * b ^ 4) + (360 : 𝕂)⁻¹ • (a ^ 3 * b ^ 5) +")
    print("        (720 : 𝕂)⁻¹ • (a ^ 2 * b ^ 6) + (2520 : 𝕂)⁻¹ • (a * b ^ 7) +")
    print("        (20160 : 𝕂)⁻¹ • b ^ 8 -")
    print("        (z * T₇ + T₂ * T₆ + T₃ * T₅ + T₄ * T₄ + T₅ * T₃ + T₆ * T₂ + T₇ * z) from rfl,")
    # Show clauses for each y_k_8.
    for k in [3, 4, 5, 6, 7]:
        comps = list(compositions(8, k))
        print(f"    show y{k}_8 =")
        for i, c in enumerate(comps):
            prefix = "        " if i == 0 else "        + "
            print(f"{prefix}{composition_term(c)}")
        if k < 7:
            print("        from rfl,")
        else:
            print("        from rfl]")
    print("  unfold bch_octic_term")
    print("  simp only [pow_succ, pow_zero, one_mul, smul_sub, smul_add, smul_neg, smul_smul,")
    print("    mul_smul_comm, smul_mul_assoc, mul_add, add_mul, mul_sub, sub_mul, ← mul_assoc]")
    print("  match_scalars <;> ring")


if __name__ == "__main__":
    main()
